documentation, incorrect migrations_paths example missing %kernel.project_dir%
doctrine/DoctrineMigrationsBundle pull request #399
Opened 2021-02-08 04:56 UTC by LPodolski

config given in documentation:
```
doctrine_migrations:
  migrations_paths:
     'App\Migrations': 'src/App'
```

is not correct and will give error: `Migrations directory "src/App" does not exist. `

also added info about using `php bin/console make:migration` instead of `php bin/console doctrine:migrations:generate`

2021-02-08 22:28 UTC, SenseException commented on Resources/doc/index.rst
> +    $ php bin/console make:migration
This is not part of the DoctrineMigrationsBundle code and shouldn't be part of the documentation for the bundle.

2021-02-11 20:35 UTC, SenseException requested changes

2021-02-11 20:35 UTC, SenseException commented on Resources/doc/index.rst
> +            'App\Migrations': '%kernel.project_dir%/src/Migrations'
Fittimg to the key `App\Migrations`: 
```suggestion
            'App\Migrations': '%kernel.project_dir%/src/App/Migrations'
```

2021-02-19 07:24 UTC, greg0ire commented
Closing in favor of #399

2021-02-19 07:25 UTC, greg0ire commented
Closing in favor of #399

2021-02-19 07:25 UTC, closed without merging