Added condition to check that we have an active connection
doctrine/DoctrineMigrationsBundle pull request #474
Opened 2022-03-07 09:29 UTC by oleg-andreyev

Fixes #473

2022-03-07 15:53 UTC, derrabus requested changes
Can you add a test that reproduces the problem you'd like to fix?

2022-03-07 15:53 UTC, derrabus commented on Collector/MigrationsCollector.php
> +    public function collect(Request $request, Response $response, ?Throwable $exception = null): void
Adding a return type is a BC break. We cannot do this in a bugfix release.

2022-03-22 18:27 UTC, oleg-andreyev commented on Collector/MigrationsCollector.php
> +    public function collect(Request $request, Response $response, ?Throwable $exception = null)
Please note that running phpcbf is adding return type.

2022-03-22 18:43 UTC, oleg-andreyev commented
> Can you add a test that reproduces the problem you'd like to fix?

It's hard to reproduce this scenario in CI, as we need to boot entire application (without configured dbal connection) and I haven't found any "functional tests" for this bundle.

2022-04-21 09:00 UTC, oleg-andreyev commented
@derrabus any chance that you'll be able to take a look at this?

2023-04-27 07:11 UTC, nedelyux commented
@derrabus Whats problem?

2023-11-13 19:55 UTC, derrabus commented
I'm sorry that nobody has picked up this PR after my initial triage. I still don't fully understand why problem is solved here. The collector needs a valid database connection. And without one, this whole bundle doesn't make much sense.

2023-11-16 10:22 UTC, oleg-andreyev commented
> I'm sorry that nobody has picked up this PR after my initial triage. I still don't fully understand why problem is solved here. The collector needs a valid database connection. And without one, this whole bundle doesn't make much sense.

It's been awhile, let me remember.

> Collector still requires an configure connection.
When starting new project and database is not yet configured, MigrationsCollector is trying to connect to database and because of PDO timeout, page feels are hanged.

IIRC initial problem is/was with clean project, when **database is not yet configured**.
So when I install this bundle it's automatically, it's automatically starts collecting information about executed migrations 
![image](https://github.com/doctrine/DoctrineMigrationsBundle/assets/1244112/e843a78b-00cd-4b1f-a0c4-9e4d6aec7bf1)
and since **database is not yet configured** it's trying to connect to a database (hosts does not exist) and it's taking 30s (default timeout) before it's throwing an exception.

and it's not very obvious that something is wrong and developers start digging into a problem why clean project is taking 30s to load.

At least this is what I remember.

2023-11-16 10:24 UTC, oleg-andreyev commented
^^^ and the idea was: avoid collecting migrations if connection is not configured.

2023-11-16 10:26 UTC, oleg-andreyev commented
and PR that was trying to fix similar issue: https://github.com/doctrine/DoctrineMigrationsBundle/pull/428 just wrapped code with try/catch which does not prevent of trying to make a connection

2025-11-07 19:37 UTC, closed without merging

2025-11-07 19:53 UTC, greg0ire commented
This got closed when I deleted the 3.3.x branch. Sorry!