deprecation : add type declaration to MigrationCollector::reset()
doctrine/DoctrineMigrationsBundle pull request #491
Opened 2023-03-14 07:59 UTC by asuri0n

2023-03-14 09:10 UTC, derrabus commented on Collector/MigrationsCollector.php
> +     * {@inheritDoc}
That's not enough to silence the deprecation emitted by Symfony's error handler. You need to document the return type explicitly.

```suggestion
     * @return void
```

2023-03-19 23:17 UTC, SenseException requested changes
Please use a meaningful commit message as described in our [contribution guide](https://www.doctrine-project.org/contribute/index.html#crafting-meaningful-commit-messages).

2023-03-20 14:52 UTC, asuri0n commented
@SenseException I don't know how to edit my previous commit messages

2023-03-20 17:30 UTC, stof commented
you need to amend your git history locally and to force-push your branch after that

2023-03-22 00:00 UTC, SenseException commented
@asuri0n You can find infos on how to change the last commit here: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_git_amend

2023-03-22 10:46 UTC, asuri0n commented
well ... I think I screwed up the git history.... I will make a new merge request with clean commit message.

2023-03-22 11:21 UTC, greg0ire commented
> I will make a new merge request with clean commit message.

You don't need to, you can just force push once the history is good.

What you could do is

```
git reset 9432bc37ab3bc4f074425c669d8a63cc388b17df
git add --patch
git commit --verbose
git push --force-with-lease
```

2023-03-22 11:22 UTC, greg0ire commented
Cc @mpdude, regarding https://github.com/doctrine/doctrine-website/pull/473#discussion_r1129076152 :)

2023-03-22 18:54 UTC, greg0ire commented
@asuri0n there are 9 commits now. Have you tried what I recommended above?

2023-03-22 19:36 UTC, mpdude commented
If we‘d ask contributors to provide meaningful summaries in the opening comment, it would help everybody coming here for a review, and less experienced Git users could more easily change the text than with Git history rewrites and force-pushes.

Then, in the end, squash-merge and use the initial comment as the squash merge message. That also makes meaningless commits in the course of the PR („Fix CS“) irrelevant.

Would have saved us all some headache here, non? But that’s just my $.02, off topic here so I’ll just shut up 😉

2023-03-22 20:03 UTC, greg0ire commented
No no, you're right, I think it's just we didn't think of that! @asuri0n , can you please edit the body of the pull request, as suggested?

2023-03-23 09:55 UTC, asuri0n commented
It's a pretty simple pull request, I've updated the body, is it enought ?

2023-03-23 10:20 UTC, greg0ire commented
> to suspend the deprecation info msg

It would be nice to quote the message.

2023-03-23 11:18 UTC, derrabus commented
> And I think maybe you considered using `@{inheritDoc}`, but that is not enough for some reason I don't remember?

https://github.com/doctrine/DoctrineMigrationsBundle/pull/491#discussion_r1135220070

2023-03-23 11:31 UTC, greg0ire commented
Oh right :facepalm:

2023-03-23 11:40 UTC, derrabus approved these changes

2023-03-23 11:40 UTC, merged

2023-03-23 11:41 UTC, derrabus commented
Thank you @asuri0n!