Add support for --complete
doctrine/DoctrineMigrationsBundle pull request #526
Opened 2024-03-14 16:20 UTC by greg0ire

When using orm:schema-tool:update together with --complete, all assets not described by the current metadata is dropped.

This is an issue when using doctrine/migrations, because not using that option is deprecated, and because when it is used, the table that holds the migrations is dropped as well since it is not described by ORM metadata.

A solution to that is configuring an asset filter that filters out the metadata table except when running commands inside the migrations namespace.

2024-03-14 16:23 UTC, greg0ire commented on Resources/config/services.xml
> +        </service>
This is the part I am not sure about, because I have been enable to test it. I've tried accessing the schema filter manager definition in order to inspect it after the compiler pass, like this:

```php
    public function testItRegistersTheSchemaFilterListener(): void
    {
        $container = $this->getContainer([]);

        $container->getDefinition('doctrine.dbal.schema_asset_filter_manager')->setPublic(true);
        $container->compile();

        $container->get('doctrine.dbal.schema_asset_filter_manager');
    }
```

That last line results in 

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "doctrine.dbal.schema_asset_filter_manager" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

Any ideas how to test this?

2024-03-14 19:09 UTC, greg0ire commented
Cc @flyingdr :)

2024-03-17 16:13 UTC, wmouwen commented on Resources/config/services.xml
> +        </service>
`doctrine.dbal.schema_asset_filter_manager` is defined as an abstract. The container builder removes unused and/or abstract definitions during its compilation causing the service to be hidden.

An example fix, not per se the wanted fix, could be:

```php
$container
  ->getDefinition('doctrine.dbal.schema_asset_filter_manager')
  ->setAbstract(false)
  ->setArgument(0, [])
  ->setPublic(true);
```

2025-01-10 07:05 UTC, christian-kolb commented
Anything I can do to get this over the finish line? Would love to be able to remove the workaround we've got in our app 🙂

2025-01-10 10:53 UTC, greg0ire commented
You could test it on your application and confirm whether it works or not.

2025-01-10 13:52 UTC, christian-kolb commented
@greg0ire Ok, I will. Are the conflicts which are mentioned by the PR going to be a stumbling block for it?

2025-01-10 14:12 UTC, christian-kolb commented
@greg0ire Unfortunately it already fails on `cache:clear`:

```
 php bin/console cache:clear
[2025-01-10T15:06:13.071685+01:00] console.CRITICAL: Error thrown while running command "cache:clear". Message: "Class "Doctrine\Migrations\EventListener\SchemaFilterListener" not found" {"exception":"[object] (Error(code: 0): Class \"Doctrine\\Migrations\\EventListener\\SchemaFilterListener\" not found at /var/www/html/api/var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:703)","command":"cache:clear","message":"Class \"Doctrine\\Migrations\\EventListener\\SchemaFilterListener\" not found"} []
[2025-01-10T15:06:13.071685+01:00] console.CRITICAL: Error thrown while running command "cache:clear". Message: "Class "Doctrine\Migrations\EventListener\SchemaFilterListener" not found" {"exception":"[object] (Error(code: 0): Class \"Doctrine\\Migrations\\EventListener\\SchemaFilterListener\" not found at /var/www/html/api/var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:703)","command":"cache:clear","message":"Class \"Doctrine\\Migrations\\EventListener\\SchemaFilterListener\" not found"} []
[2025-01-10T15:06:13.072295+01:00] console.DEBUG: Command "cache:clear" exited with code "1" {"command":"cache:clear","code":1} []
[2025-01-10T15:06:13.072369+01:00] php.CRITICAL: Uncaught Error: Class "Doctrine\Migrations\EventListener\SchemaFilterListener" not found {"exception":"[object] (Error(code: 0): Class \"Doctrine\\Migrations\\EventListener\\SchemaFilterListener\" not found at /var/www/html/api/var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:703)"} []
[2025-01-10T15:06:13.072369+01:00] php.CRITICAL: Uncaught Error: Class "Doctrine\Migrations\EventListener\SchemaFilterListener" not found {"exception":"[object] (Error(code: 0): Class \"Doctrine\\Migrations\\EventListener\\SchemaFilterListener\" not found at /var/www/html/api/var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:703)"} []
Symfony\Component\ErrorHandler\Error\ClassNotFoundError^ {#1415
  #message: """
    Attempted to load class "SchemaFilterListener" from namespace "Doctrine\Migrations\EventListener".\n
    Did you forget a "use" statement for "Doctrine\Bundle\MigrationsBundle\EventListener\SchemaFilterListener"?
    """
  #code: 0
  #file: "./var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php"
  #line: 703
  trace: {
    ./var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:703 {
      ContainerXRKMlYx\App_KernelDevDebugContainer::getDoctrine_Dbal_DefaultConnectionService($container)^
      › $b->setSchemaManagerFactory(($container->privates['doctrine.dbal.legacy_schema_manager_factory'] ??= new \Doctrine\DBAL\Schema\LegacySchemaManagerFactory()));
      › $b->setSchemaAssetsFilter(new \Doctrine\Bundle\DoctrineBundle\Dbal\SchemaAssetsFilterManager([new \Doctrine\Bundle\DoctrineBundle\Dbal\RegexSchemaAssetFilter('~^(?!(?:domain_messages)|(?:domain_snapshots)|(?:cache_items)|(?:projection_handler_event_lock))~'), ($container->privates['doctrine_migrations.schema_filter_listener'] ??= new \Doctrine\Migrations\EventListener\SchemaFilterListener())]));
      › $b->setMiddlewares([new \Doctrine\DBAL\Logging\Middleware(($container->privates['monolog.logger.doctrine'] ?? self::getMonolog_Logger_DoctrineService($container))), $c]);
    }
    ./var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:1379 { …}
    ./var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:1363 { …}
    ./var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:653 { …}
    ./var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:556 { …}
    ./var/cache/dev/ContainerXRKMlYx/getConsoleProfilerListenerService.php:23 { …}
    ./var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:506 { …}
    ./var/cache/dev/ContainerXRKMlYx/App_KernelDevDebugContainer.php:768 { …}
    ./vendor/symfony/event-dispatcher/EventDispatcher.php:221 { …}
    ./vendor/symfony/event-dispatcher/EventDispatcher.php:70 { …}
    ./vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:252 { …}
    ./vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:116 { …}
    ./vendor/symfony/console/Application.php:1044 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:123 { …}
    ./vendor/symfony/console/Application.php:316 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:77 { …}
    ./vendor/symfony/console/Application.php:167 { …}
    ./bin/console:38 { …}
  }
}
```

The service is mentioned in `services.xml` as `Doctrine\Migrations\EventListener\SchemaFilterListener` but the namespace in the class seems to be `Doctrine\Bundle\MigrationsBundle\EventListener`.

Fixing it to be the following seems to be necessary:

```xml
<service id="doctrine_migrations.schema_filter_listener" class="Doctrine\Bundle\MigrationsBundle\EventListener\SchemaFilterListener">
```

But even with this added, when running: `php bin/console doctrine:schema:update --dump-sql` it results in:

```
DROP TABLE migration_versions;
```

2025-01-10 14:13 UTC, christian-kolb commented
@greg0ire Is there anything that needs to be configured for it to work?

2025-01-10 14:27 UTC, greg0ire commented on Resources/config/services.xml
> +        <service id="doctrine_migrations.schema_filter_listener" class="Doctrine\Migrations\EventListener\SchemaFilterListener">
```suggestion
        <service id="doctrine_migrations.schema_filter_listener" class="Doctrine\Bundle\MigrationsBundle\EventListener\SchemaFilterListener">
```

2025-01-10 14:28 UTC, greg0ire commented
> Ok, I will. Are the conflicts which are mentioned by the PR going to be a stumbling block for it?

No.


Thanks for your suggestion, I applied it. I will need to fix the conflicts for this to get merged though.

> Is there anything that needs to be configured for it to work?

No, I don't think so…

2025-01-10 14:29 UTC, greg0ire commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
@christian-kolb You could use a debugger or a simple print statement to see if this gets executed

2025-01-10 14:36 UTC, christian-kolb commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
It is executed, the drop statement is still generated with the new version though.

2025-01-10 18:25 UTC, greg0ire commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
Does the comparison on line 33 ever return `true`?

2025-01-11 09:16 UTC, christian-kolb commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
@greg0ire With this changes, I get the following output:
![CleanShot 2025-01-11 at 10 15 32@2x](https://github.com/user-attachments/assets/cdb51a8f-7692-43e0-832a-537393c8d30b)

```
php bin/console doc:sch:up --dump-sql
bool(true)
bool(true)
DROP TABLE migration_versions;
```

2025-01-11 09:50 UTC, greg0ire commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
Ah sorry, I didn't spot the `!==`… the real question is: "does it ever return `false`" and it looks like it doesn't. So either `$asset`, which you could `var_dump` is never the name of the migrations table, or there is a subtle difference, like maybe the schema is included in `$asset` and not in `(new TableMetadataStorageConfiguration())->getTableName())`.

Aside, when you post code, can you post text and not an image? It will make it possible for me to use copy/paste.

2025-01-11 10:09 UTC, christian-kolb commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
With:
```php
public function __invoke($asset): bool
{
    if (! $this->enabled) {
        return true;
    }

    if ($asset instanceof AbstractAsset) {
        $asset = $asset->getName();
    }

    var_dump($asset);
    var_dump((new TableMetadataStorageConfiguration())->getTableName());
    var_dump($asset !== (new TableMetadataStorageConfiguration())->getTableName());

    return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
}
```

it leads to the following output:

```
php bin/console doc:sch:up --dump-sql
string(25) "messenger_messages_id_seq"
string(27) "doctrine_migration_versions"
bool(true)
string(18) "migration_versions"
string(27) "doctrine_migration_versions"
bool(true)
DROP TABLE migration_versions;
```

2025-01-11 10:11 UTC, christian-kolb commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
So the problem is, that it's not getting the table name from the configuration of `doctrine_migrations.yaml`, but only the default one. Which makes sense as it's defined as `new TableMetadataStorageConfiguration()`.

2025-01-11 10:22 UTC, greg0ire commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
Great job, that makes sense. We should find a way to inject the right table name.

2025-01-11 10:50 UTC, greg0ire commented on src/DependencyInjection/DoctrineMigrationsExtension.php
> +            $container->removeDefinition('doctrine_migrations.schema_filter_listener');
When a user defines their own storage class, there is no telling what they are going to do… they might even not store it in a database. At this point they're one their own.

2025-01-11 10:53 UTC, greg0ire commented on EventListener/SchemaFilterListener.php
> +        return $asset !== (new TableMetadataStorageConfiguration())->getTableName();
@christian-kolb I pushed a new version, please try it.

2025-01-11 11:08 UTC, greg0ire commented on Resources/config/services.xml
> +        </service>
OK… I guess since it's abstract, I should try to retrieve a concrete definition inheriting from it. I inspected the container, and there does not seem to be any :(

2025-01-11 12:17 UTC, christian-kolb commented
@greg0ire Awesome, now it's working. Now I get what I should get:

```
[OK] Nothing to update - your database is already in sync with the current entity metadata.  
```

2025-01-11 12:36 UTC, greg0ire commented
Thanks for helping moving this forward! Let's get this reviewed now.

2025-01-15 23:16 UTC, SenseException requested changes

2025-01-15 23:16 UTC, SenseException commented on src/EventListener/SchemaFilterListener.php
> + * Acts as a schema filter able that hides the migration metadata table except
Sounds weird. Did you mean something like this?
```suggestion
 * Acts as a schema filterable that hides the migration metadata table except
```

2025-01-15 23:16 UTC, SenseException commented on tests/Collector/EventListener/SchemaFilterListenerTest.php
> +    }
I don't understand this use case. When do you need to disable it in userland by calling the public disable-method?

2025-01-16 07:33 UTC, greg0ire commented on src/EventListener/SchemaFilterListener.php
> + * Acts as a schema filter able that hides the migration metadata table except
I think I changed my mind about how to phrase this mid-sentence, I'll rephrase.

2025-01-16 07:38 UTC, greg0ire commented on tests/Collector/EventListener/SchemaFilterListenerTest.php
> +    }
:thinking: I suspect I might have written that one before writing the next use case. I'll remove it and make the method private, if it's needed in userland, people can make it public later.

2025-01-16 19:16 UTC, SenseException commented on src/EventListener/SchemaFilterListener.php
> + * Acts as a schema filter able that hides the migration metadata table except
That's what happens to me all the time :smile:

2025-01-16 19:17 UTC, SenseException approved these changes

2025-01-16 20:19 UTC, merged

2025-01-18 00:03 UTC, kevinpapst commented
@greg0ire I am having issues since upgrading the bundle
```
 Upgrading doctrine/doctrine-migrations-bundle (3.3.1 => 3.4.0)
```

I am running in a CI pipeline:
```
bin/console doctrine:schema:drop --force --full-database
```
which now suddenly does NOT delete the `migration_versions` table anymore.

The next command I am running is actually the migrations themselves, which now fail with:
```
Failed to execute a migrations: An exception occurred while executing a query: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'migration_versions' already exists"
```

A workaround for now is to run: 
```
bin/console doctrine:query:sql --sql="DROP TABLE IF EXISTS migration_versions"
```
but that shouldn't be necessary when I use `--full-database`.

2025-01-24 14:35 UTC, haxus01 commented on src/DependencyInjection/DoctrineMigrationsExtension.php
> +            } else {
After implementing these changes, running the migration results in the following exception:
`SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "doctrine_migration_versions" already exists.`